name: joel_security_entry
description: "Security Check-In Final Project"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  qr_code_scanner: ^1.0.1
  sqflite: ^2.3.2
  path: ^1.9.0
  qr_flutter: ^4.1.0
  path_provider: 2.1.2
  intl: ^0.19.0
  riverpod: ^2.4.9
  get: ^4.6.6
  open_file: ^3.3.2
  shared_preferences: ^2.2.2
  objectbox: ^2.5.1
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  objectbox_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/trust_academy_logo.jpg
